# Generated by Django 2.0 on 2017-12-17 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('objetivo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NotaDeProva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('leitura', 'Leitura'), ('escrita', 'Escrita')], max_length=100)),
                ('nota', models.FloatField()),
                ('aluno', models.ManyToManyField(to='ecweb.Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='PresencaDeAula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ManyToManyField(to='ecweb.Aluno')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecweb.Aula')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nivel', models.CharField(choices=[('begginer', 'Begginer'), ('advanced', 'Advanced')], max_length=100)),
                ('alunos', models.ManyToManyField(to='ecweb.Aluno')),
                ('professores', models.ManyToManyField(to='ecweb.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='prova',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecweb.Turma'),
        ),
        migrations.AddField(
            model_name='notadeprova',
            name='prova',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecweb.Prova'),
        ),
        migrations.AddField(
            model_name='aula',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecweb.Turma'),
        ),
        migrations.AddField(
            model_name='aula',
            name='videos',
            field=models.ManyToManyField(to='ecweb.YoutubeVideo'),
        ),
    ]
